<a href="https://colab.research.google.com/github/ridanoor0110/DSC_110/blob/main/week5_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
#dataframe in python is the equivalent of table in SQL.

df = pd.read_csv("https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv")

df.head()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN

In [3]:
df.tail()
#prints last 5 rows

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
11928,142306.0,1.0,9.0,2.0,NaN,15.4,128.0,NaN,2.0,NaN,NaN
11929,142307.0,2.0,49.0,4.0,5.0,NaN,143.8,127.0,1.0,6.2,NaN
11930,142308.0,1.0,50.0,2.0,4.0,26.4,173.3,106.0,2.0,NaN,NaN
11931,142309.0,1.0,40.0,2.0,4.0,25.5,179.1,127.0,2.0,5.2,96.0
11932,142310.0,2.0,80.0,3.0,3.0,27.6,161.7,128.0,2.0,5.3,NaN

In [6]:
df.tail(10)
#prints last 10 rows

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
11923,142301.0,2.0,80.0,3.0,5.0,30.5,164.3,NaN,2.0,5.6,110.0
11924,142302.0,1.0,70.0,3.0,4.0,21.4,161.5,126.0,2.0,5.2,NaN
11925,142303.0,2.0,69.0,7.0,3.0,27.9,159.2,129.0,1.0,8.1,160.0
11926,142304.0,1.0,14.0,2.0,NaN,18.5,162.4,116.0,2.0,NaN,NaN
11927,142305.0,2.0,76.0,1.0,1.0,26.4,151.4,139.0,3.0,6.0,132.0
11928,142306.0,1.0,9.0,2.0,NaN,15.4,128.0,NaN,2.0,NaN,NaN
11929,142307.0,2.0,49.0,4.0,5.0,NaN,143.8,127.0,1.0,6.2,NaN
11930,142308.0,1.0,50.0,2.0,4.0,26.4,173.3,106.0,2.0,NaN,NaN
11931,142309.0,1.0,40.0,2.0,4.0,25.5,179.1,127.0,2.0,5.2,96.0
11932,142310.0,2.0,80.0,3.0,3.0,27.6,161.7,128.0,2.0,5.3,NaN

In [7]:
df.shape
#prints number of rows and the numbers of fields

(11933, 11)

In [9]:
df.shape[0]
#prints number of rows

11933

In [11]:
df.shape[1]
#prints number of fields/columns

11

In [12]:
n_rows = df.shape[0]
n_columns = df.shape[1]
print(f"my data set contains {n_rows} rows and {n_columns} columns")
#assigned the number of rows and number of columns to their respective variables and then printed them along with some text that makes the data interpretable by the user

my data set contains 11933 rows and 11 columns

Boolean

In [13]:
True + True

2

In [14]:
True + False

1

In [16]:
#true represents 1 and false represents 0

Data Cleaning

In [15]:
#isna
#this function checks to find missing data
#looks for missing values in bmi field in first 5 rows

df['bmi'].isna().head()

0    False
1    False
2    False
3    False
4     True
Name: bmi, dtype: bool

In [17]:
df['bmi'].isna().sum()
#gives num of rows where na = true
#in other words, number of rows missing a value which in this case is 3462

np.int64(3462)

We will create a subset for people over 18 years only and see how many BMI values are missing.

In [19]:
df_adults = df[df['age'] > 18]
df_adults.shape[0]
#verifies that our number of rows has changed to a smaller number to confirm we have created a data set

7969

In [21]:
df_adults['age'].min()
#verifies the minimum age to make sure our subset is successful

19.0

In [22]:
df_adults['bmi'].isna().sum()
#see how many missing values are there for bmi for our adult dataset

np.int64(1878)

student work: do the same for education and have the output in f string

In [26]:
naadulteducation = df_adults['education'].isna().sum()
naeducation = df['education'].isna().sum()
print(f"education information is missing for {naadulteducation} adults but is missing for {naeducation} individuals overall in the data set")

education information is missing for 175 adults but is missing for 4139 individuals overall in the data set

In [27]:
#check missingness in the entire dataframe
df.isna().sum()

id                    0
gender                0
age                   0
race_ethnicity        0
education          4139
bmi                3462
height_cm          3434
systolic_bp        4416
has_diabetes        193
hba1c              5218
fasting_glucose    8261
dtype: int64

In [28]:
round(df.isna().mean()*100,1)

id                  0.0
gender              0.0
age                 0.0
race_ethnicity      0.0
education          34.7
bmi                29.0
height_cm          28.8
systolic_bp        37.0
has_diabetes        1.6
hba1c              43.7
fasting_glucose    69.2
dtype: float64

What do we do with missing data values?
1. dropping rows
2. fill in with the mean

In [29]:
#drop all rows that have any missing values
df_complete = df.dropna()
df_complete.shape[0]

3075

In [32]:
#drop only the rows where select fields have missing values
df_complete_bmi = df.dropna(subset = ['bmi'])
df_complete_bmi.shape[0]

8471

In [37]:
#filling na with mean, zero or any other variable
#get mean and assign it to a variable
mean_bp = df['systolic_bp'].mean()
print (mean_bp)

df['systolic_bp'] = df['systolic_bp'].fillna(mean_bp)

119.28854596248502

In [38]:
#verify that the na fields have been replaced with the mean for systolic_Bp
df['systolic_bp'].isna().sum()

np.int64(0)

transforming variables

In [42]:
def bmi_check(bmi):
  if bmi < 18.5:
    bmi_result = "underweight"
  elif bmi < 25:
    bmi_result = "normal"
  elif bmi < 30:
    bmi_result = "overweight"
  else:
    bmi_result = "obese"
  return bmi_result

df['bmi_category'] = df['bmi'].apply(bmi_check)
#applies the bmi check function to our dataset for the bmi field

#verify it with value_counts()

df['bmi_category'].value_counts()
#counts the number of output for each category indicated by the function

bmi_category
obese          6161
normal         2372
overweight     2205
underweight    1195
Name: count, dtype: int64

In [43]:
#new function called "cut"
#does same thing as earlier but summarizes in much less lines of code

df['bmi_category2'] = pd.cut(df['bmi'],
                             bins = [0, 18.5, 25, 30, 100],
                             labels = ['underweight', 'normal', 'obese', 'overweight'])

#verify it
df['bmi_category2'].value_counts()

bmi_category2
overweight     2666
normal         2400
obese          2189
underweight    1216
Name: count, dtype: int64

In [45]:
#see missing values
df['bmi_category2'].value_counts(dropna = False)

bmi_category2
NaN            3462
overweight     2666
normal         2400
obese          2189
underweight    1216
Name: count, dtype: int64